
# GitLab CI Docker Image
image: node:6.9.5

# GitLab CI Docker postgresql
services:
      - postgres:9.3.4

# Build - Build necessary JS files
# Test - Run tests
stages:
  - build
  - test
# Configuration
variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: custom_db
  POSTGRES_USER: custom_user
  POSTGRES_PASSWORD: custom_pass

# Job: Build
# Installs npm packages
# Passes node_modules/, dist/ onto next steps using artifacts
build:
  stage: build
  script:
    - npm install --only=dev
  artifacts:
    paths:
      - node_modules/

connect:
  image: postgres
  stage: test
  script:
  # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

# Job: Test
# Run tests against our application
test:
  stage: test
  script:
    - npm test
